wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
    start_time: 1681425761
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      4: 3.7.6
      5: 0.12.21
      8:
      - 5
kl_coef:
  desc: null
  value: 1.0
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: null
weight_decay:
  desc: null
  value: 1.0e-08
